# Generated by Django 5.1.1 on 2024-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_player_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='match',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='score',
            new_name='score_red',
        ),
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='score_yellow',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
