# Generated by Django 5.1.1 on 2024-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_game_match_rename_score_game_score_red_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team',
        ),
        migrations.AddField(
            model_name='game',
            name='red_team',
            field=models.ManyToManyField(related_name='red_team', to='leaderboard.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='yellow_team',
            field=models.ManyToManyField(related_name='yellow_team', to='leaderboard.player'),
        ),
    ]
