# Generated by Django 5.1.1 on 2024-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_remove_game_player_remove_game_team_game_red_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='trueskill_rating',
            new_name='mu',
        ),
        migrations.AddField(
            model_name='player',
            name='sigma',
            field=models.FloatField(default=8.33),
        ),
    ]
