# Generated by Django 5.1.1 on 2024-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_rename_trueskill_rating_player_mu_player_sigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='red_team_mu_change',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='yellow_team_mu_change',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
