# Generated by Django 5.1.1 on 2024-09-22 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_game_red_team_mu_change_game_yellow_team_mu_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
