# Generated by Django 5.1.1 on 2024-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_alter_game_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow')], max_length=10, null=True),
        ),
    ]
